CC=gcc
CFLAGS=
LDFLAGS=
# EXE=netlink_user
# SRC=netlink_user.c

# EXE=netlink_user_sendto_recvfrom
# SRC=netlink_user_sendto_recvfrom.c

EXE=netlink_user_send_recv
SRC=netlink_user_send_recv.c

all:
	gcc -o $(EXE) $(CFLAGS) $(LDFLAGS) $(SRC)

clean:
	rm -rf $(EXE)
